import { cpuMasterDb, type CpuItem } from "./hardwareMasterDb";

export interface CPU {
  id: string;

  name: string;
  brand: "AMD" | "Intel";

  socket: string;

  cores: number;
  threads: number;

  baseClock: number;
  boostClock: number;

  cache: number;

  tdp: number;

  igpu: boolean;

  ddr: "DDR4" | "DDR5";

  pcie: "4.0" | "5.0";

  releaseYear: number;

  gameScore: number;
  workScore: number;
  aiScore: number;

  priceTier: "budget" | "mid" | "high" | "enthusiast";
}

export const cpus: CPU[] = [
  {
    id: "i9-14900k",
    name: "Core i9-14900K",
    brand: "Intel",
    socket: "LGA1700",
    cores: 24,
    threads: 32,
    baseClock: 3.2,
    boostClock: 6.0,
    cache: 36,
    tdp: 125,
    igpu: true,
    ddr: "DDR5",
    pcie: "5.0",
    releaseYear: 2023,
    gameScore: 98,
    workScore: 99,
    aiScore: 95,
    priceTier: "enthusiast",
  },
  {
    id: "i7-14700k",
    name: "Core i7-14700K",
    brand: "Intel",
    socket: "LGA1700",
    cores: 20,
    threads: 28,
    baseClock: 3.4,
    boostClock: 5.6,
    cache: 33,
    tdp: 125,
    igpu: true,
    ddr: "DDR5",
    pcie: "5.0",
    releaseYear: 2023,
    gameScore: 95,
    workScore: 96,
    aiScore: 90,
    priceTier: "high",
  },
  {
    id: "i5-14600k",
    name: "Core i5-14600K",
    brand: "Intel",
    socket: "LGA1700",
    cores: 14,
    threads: 20,
    baseClock: 3.5,
    boostClock: 5.3,
    cache: 24,
    tdp: 125,
    igpu: true,
    ddr: "DDR5",
    pcie: "5.0",
    releaseYear: 2024,
    gameScore: 92,
    workScore: 91,
    aiScore: 84,
    priceTier: "mid",
  },
  {
    id: "i5-14400f",
    name: "Core i5-14400F",
    brand: "Intel",
    socket: "LGA1700",
    cores: 10,
    threads: 16,
    baseClock: 2.5,
    boostClock: 4.7,
    cache: 20,
    tdp: 65,
    igpu: false,
    ddr: "DDR5",
    pcie: "5.0",
    releaseYear: 2024,
    gameScore: 84,
    workScore: 84,
    aiScore: 75,
    priceTier: "budget",
  },
  {
    id: "ultra9-285k",
    name: "Core Ultra 9 285K",
    brand: "Intel",
    socket: "LGA1851",
    cores: 24,
    threads: 24,
    baseClock: 3.7,
    boostClock: 5.7,
    cache: 36,
    tdp: 125,
    igpu: true,
    ddr: "DDR5",
    pcie: "5.0",
    releaseYear: 2024,
    gameScore: 97,
    workScore: 98,
    aiScore: 97,
    priceTier: "enthusiast",
  },
  {
    id: "ultra7-265k",
    name: "Core Ultra 7 265K",
    brand: "Intel",
    socket: "LGA1851",
    cores: 20,
    threads: 20,
    baseClock: 3.9,
    boostClock: 5.5,
    cache: 30,
    tdp: 125,
    igpu: true,
    ddr: "DDR5",
    pcie: "5.0",
    releaseYear: 2024,
    gameScore: 92,
    workScore: 96,
    aiScore: 93,
    priceTier: "high",
  },
  {
    id: "ultra5-245f",
    name: "Core Ultra 5 245F",
    brand: "Intel",
    socket: "LGA1851",
    cores: 14,
    threads: 14,
    baseClock: 3.5,
    boostClock: 5.2,
    cache: 24,
    tdp: 125,
    igpu: false,
    ddr: "DDR5",
    pcie: "5.0",
    releaseYear: 2024,
    gameScore: 88,
    workScore: 86,
    aiScore: 80,
    priceTier: "mid",
  },
  {
    id: "r9-9950x",
    name: "Ryzen 9 9950X",
    brand: "AMD",
    socket: "AM5",
    cores: 16,
    threads: 32,
    baseClock: 4.3,
    boostClock: 5.7,
    cache: 64,
    tdp: 170,
    igpu: true,
    ddr: "DDR5",
    pcie: "5.0",
    releaseYear: 2025,
    gameScore: 99,
    workScore: 99,
    aiScore: 99,
    priceTier: "enthusiast",
  },
  {
    id: "r7-9700x",
    name: "Ryzen 7 9700X",
    brand: "AMD",
    socket: "AM5",
    cores: 8,
    threads: 16,
    baseClock: 3.8,
    boostClock: 5.5,
    cache: 32,
    tdp: 65,
    igpu: true,
    ddr: "DDR5",
    pcie: "5.0",
    releaseYear: 2024,
    gameScore: 93,
    workScore: 91,
    aiScore: 86,
    priceTier: "mid",
  },
  {
    id: "r7-9800x3d",
    name: "Ryzen 7 9800X3D",
    brand: "AMD",
    socket: "AM5",
    cores: 8,
    threads: 16,
    baseClock: 4.2,
    boostClock: 5.2,
    cache: 96,
    tdp: 120,
    igpu: true,
    ddr: "DDR5",
    pcie: "5.0",
    releaseYear: 2025,
    gameScore: 100,
    workScore: 94,
    aiScore: 90,
    priceTier: "high",
  },
  {
    id: "r5-9600x",
    name: "Ryzen 5 9600X",
    brand: "AMD",
    socket: "AM5",
    cores: 6,
    threads: 12,
    baseClock: 3.9,
    boostClock: 5.4,
    cache: 32,
    tdp: 65,
    igpu: true,
    ddr: "DDR5",
    pcie: "5.0",
    releaseYear: 2024,
    gameScore: 90,
    workScore: 88,
    aiScore: 82,
    priceTier: "mid",
  },
  {
    id: "r5-5600x",
    name: "Ryzen 5 5600X",
    brand: "AMD",
    socket: "AM4",
    cores: 6,
    threads: 12,
    baseClock: 3.7,
    boostClock: 4.6,
    cache: 32,
    tdp: 65,
    igpu: false,
    ddr: "DDR4",
    pcie: "4.0",
    releaseYear: 2020,
    gameScore: 80,
    workScore: 76,
    aiScore: 70,
    priceTier: "budget",
  },
  {
    id: "r7-7800x3d",
    name: "Ryzen 7 7800X3D",
    brand: "AMD",
    socket: "AM5",
    cores: 8,
    threads: 16,
    baseClock: 4.2,
    boostClock: 5.0,
    cache: 96,
    tdp: 120,
    igpu: true,
    ddr: "DDR5",
    pcie: "5.0",
    releaseYear: 2023,
    gameScore: 98,
    workScore: 93,
    aiScore: 88,
    priceTier: "high",
  },
  {
    id: "r7-7500f",
    name: "Ryzen 7 7500F",
    brand: "AMD",
    socket: "AM5",
    cores: 8,
    threads: 16,
    baseClock: 3.7,
    boostClock: 5.0,
    cache: 32,
    tdp: 65,
    igpu: false,
    ddr: "DDR5",
    pcie: "5.0",
    releaseYear: 2023,
    gameScore: 88,
    workScore: 86,
    aiScore: 78,
    priceTier: "mid",
  },
  {
    id: "r5-5600",
    name: "Ryzen 5 5600",
    brand: "AMD",
    socket: "AM4",
    cores: 6,
    threads: 12,
    baseClock: 3.5,
    boostClock: 4.4,
    cache: 32,
    tdp: 65,
    igpu: true,
    ddr: "DDR4",
    pcie: "4.0",
    releaseYear: 2020,
    gameScore: 78,
    workScore: 74,
    aiScore: 68,
    priceTier: "budget",
  },
];

export const cpuMasterItems: CpuItem[] = cpuMasterDb;