import { getAllGpus } from "../../src/utils/hardwareLookup";
import { buildAdditionalGpus } from "../lib/hardwareScoring";

export interface GPU {
  id: string;

  name: string;
  brand: "NVIDIA" | "AMD" | "Intel";

  vram: number;
  memoryType: string;

  tgp: number;

  dlss: boolean;
  fsr: boolean;
  xess: boolean;

  rayTracing: boolean;

  pcie: "3.0" | "4.0" | "5.0";

  releaseYear: number;

  gameScore: number;
  workScore: number;
  aiScore: number;

  priceTier: "budget" | "mid" | "high" | "enthusiast";
}

// 수작업으로 큐레이션된 앵커 데이터. gameScore/workScore/aiScore/priceTier는 여기서만 수동 유지하고,
// 아래 additionalGpus는 이 배열을 학습 앵커로 삼아 점수를 추정한다.
const curatedGpus: GPU[] = [
  {
    id: "rtx4070-super",
    name: "GeForce RTX 4070 SUPER",
    brand: "NVIDIA",
    vram: 12,
    memoryType: "GDDR6X",
    tgp: 220,
    dlss: true,
    fsr: false,
    xess: false,
    rayTracing: true,
    pcie: "4.0",
    releaseYear: 2024,
    gameScore: 96,
    workScore: 92,
    aiScore: 91,
    priceTier: "high",
  },
  {
    id: "rtx4070-ti-super",
    name: "GeForce RTX 4070 Ti SUPER",
    brand: "NVIDIA",
    vram: 16,
    memoryType: "GDDR6X",
    tgp: 285,
    dlss: true,
    fsr: false,
    xess: false,
    rayTracing: true,
    pcie: "4.0",
    releaseYear: 2024,
    gameScore: 98,
    workScore: 95,
    aiScore: 96,
    priceTier: "enthusiast",
  },
  {
    id: "rtx5080",
    name: "GeForce RTX 5080",
    brand: "NVIDIA",
    vram: 16,
    memoryType: "GDDR7",
    tgp: 360,
    dlss: true,
    fsr: false,
    xess: false,
    rayTracing: true,
    pcie: "5.0",
    releaseYear: 2025,
    gameScore: 99,
    workScore: 97,
    aiScore: 98,
    priceTier: "enthusiast",
  },
  {
    id: "rtx5070",
    name: "GeForce RTX 5070",
    brand: "NVIDIA",
    vram: 12,
    memoryType: "GDDR7",
    tgp: 250,
    dlss: true,
    fsr: false,
    xess: false,
    rayTracing: true,
    pcie: "5.0",
    releaseYear: 2025,
    gameScore: 97,
    workScore: 94,
    aiScore: 95,
    priceTier: "high",
  },
  {
    id: "gtx960",
    name: "GeForce GTX 960",
    brand: "NVIDIA",
    vram: 4,
    memoryType: "GDDR5",
    tgp: 120,
    dlss: false,
    fsr: false,
    xess: false,
    rayTracing: false,
    pcie: "3.0",
    releaseYear: 2015,
    gameScore: 40,
    workScore: 35,
    aiScore: 20,
    priceTier: "budget",
  },
  {
    id: "gtx970",
    name: "GeForce GTX 970",
    brand: "NVIDIA",
    vram: 4,
    memoryType: "GDDR5",
    tgp: 145,
    dlss: false,
    fsr: false,
    xess: false,
    rayTracing: false,
    pcie: "3.0",
    releaseYear: 2014,
    gameScore: 50,
    workScore: 45,
    aiScore: 25,
    priceTier: "budget",
  },
  {
    id: "gtx980",
    name: "GeForce GTX 980",
    brand: "NVIDIA",
    vram: 4,
    memoryType: "GDDR5",
    tgp: 165,
    dlss: false,
    fsr: false,
    xess: false,
    rayTracing: false,
    pcie: "3.0",
    releaseYear: 2014,
    gameScore: 60,
    workScore: 55,
    aiScore: 30,
    priceTier: "mid",
  },
  {
    id: "gtx980ti",
    name: "GeForce GTX 980 Ti",
    brand: "NVIDIA",
    vram: 6,
    memoryType: "GDDR5",
    tgp: 250,
    dlss: false,
    fsr: false,
    xess: false,
    rayTracing: false,
    pcie: "3.0",
    releaseYear: 2015,
    gameScore: 70,
    workScore: 65,
    aiScore: 35,
    priceTier: "mid",
  },
  {
    id: "gtx1050",
    name: "GeForce GTX 1050",
    brand: "NVIDIA",
    vram: 2,
    memoryType: "GDDR5",
    tgp: 75,
    dlss: false,
    fsr: false,
    xess: false,
    rayTracing: false,
    pcie: "3.0",
    releaseYear: 2016,
    gameScore: 45,
    workScore: 40,
    aiScore: 22,
    priceTier: "budget",
  },
  {
    id: "gtx1050ti",
    name: "GeForce GTX 1050 Ti",
    brand: "NVIDIA",
    vram: 4,
    memoryType: "GDDR5",
    tgp: 75,
    dlss: false,
    fsr: false,
    xess: false,
    rayTracing: false,
    pcie: "3.0",
    releaseYear: 2016,
    gameScore: 50,
    workScore: 45,
    aiScore: 24,
    priceTier: "budget",
  },
  {
    id: "gtx1060",
    name: "GeForce GTX 1060",
    brand: "NVIDIA",
    vram: 6,
    memoryType: "GDDR5",
    tgp: 120,
    dlss: false,
    fsr: false,
    xess: false,
    rayTracing: false,
    pcie: "3.0",
    releaseYear: 2016,
    gameScore: 65,
    workScore: 60,
    aiScore: 32,
    priceTier: "mid",
  },
  {
    id: "gtx1070",
    name: "GeForce GTX 1070",
    brand: "NVIDIA",
    vram: 8,
    memoryType: "GDDR5",
    tgp: 150,
    dlss: false,
    fsr: false,
    xess: false,
    rayTracing: false,
    pcie: "3.0",
    releaseYear: 2016,
    gameScore: 75,
    workScore: 70,
    aiScore: 40,
    priceTier: "mid",
  },
  {
    id: "gtx1080",
    name: "GeForce GTX 1080",
    brand: "NVIDIA",
    vram: 8,
    memoryType: "GDDR5X",
    tgp: 180,
    dlss: false,
    fsr: false,
    xess: false,
    rayTracing: false,
    pcie: "3.0",
    releaseYear: 2016,
    gameScore: 85,
    workScore: 80,
    aiScore: 50,
    priceTier: "high",
  },
  {
    id: "gtx1080ti",
    name: "GeForce GTX 1080 Ti",
    brand: "NVIDIA",
    vram: 11,
    memoryType: "GDDR5X",
    tgp: 250,
    dlss: false,
    fsr: false,
    xess: false,
    rayTracing: false,
    pcie: "3.0",
    releaseYear: 2017,
    gameScore: 95,
    workScore: 90,
    aiScore: 55,
    priceTier: "high",
  },
  {
    id: "gtx1650",
    name: "GeForce GTX 1650",
    brand: "NVIDIA",
    vram: 4,
    memoryType: "GDDR5",
    tgp: 75,
    dlss: false,
    fsr: false,
    xess: false,
    rayTracing: false,
    pcie: "3.0",
    releaseYear: 2019,
    gameScore: 55,
    workScore: 50,
    aiScore: 28,
    priceTier: "budget",
  },
  {
    id: "gtx1660",
    name: "GeForce GTX 1660",
    brand: "NVIDIA",
    vram: 6,
    memoryType: "GDDR5",
    tgp: 120,
    dlss: false,
    fsr: false,
    xess: false,
    rayTracing: false,
    pcie: "3.0",
    releaseYear: 2019,
    gameScore: 65,
    workScore: 60,
    aiScore: 32,
    priceTier: "mid",
  },
  {
    id: "gtx1660super",
    name: "GeForce GTX 1660 SUPER",
    brand: "NVIDIA",
    vram: 6,
    memoryType: "GDDR6",
    tgp: 125,
    dlss: false,
    fsr: false,
    xess: false,
    rayTracing: false,
    pcie: "3.0",
    releaseYear: 2019,
    gameScore: 70,
    workScore: 65,
    aiScore: 35,
    priceTier: "mid",
  },
  {
    id: "gtx1660ti",
    name: "GeForce GTX 1660 Ti",
    brand: "NVIDIA",
    vram: 6,
    memoryType: "GDDR6",
    tgp: 130,
    dlss: false,
    fsr: false,
    xess: false,
    rayTracing: false,
    pcie: "3.0",
    releaseYear: 2019,
    gameScore: 75,
    workScore: 70,
    aiScore: 38,
    priceTier: "mid",
  },
  {
    id: "rtx2060",
    name: "GeForce RTX 2060",
    brand: "NVIDIA",
    vram: 6,
    memoryType: "GDDR6",
    tgp: 160,
    dlss: true,
    fsr: false,
    xess: false,
    rayTracing: true,
    pcie: "3.0",
    releaseYear: 2019,
    gameScore: 70,
    workScore: 65,
    aiScore: 55,
    priceTier: "mid",
  },
  {
    id: "rtx2070",
    name: "GeForce RTX 2070",
    brand: "NVIDIA",
    vram: 8,
    memoryType: "GDDR6",
    tgp: 175,
    dlss: true,
    fsr: false,
    xess: false,
    rayTracing: true,
    pcie: "3.0",
    releaseYear: 2018,
    gameScore: 80,
    workScore: 75,
    aiScore: 65,
    priceTier: "mid",
  },
  {
    id: "rtx2070super",
    name: "GeForce RTX 2070 SUPER",
    brand: "NVIDIA",
    vram: 8,
    memoryType: "GDDR6",
    tgp: 215,
    dlss: true,
    fsr: false,
    xess: false,
    rayTracing: true,
    pcie: "3.0",
    releaseYear: 2019,
    gameScore: 85,
    workScore: 80,
    aiScore: 70,
    priceTier: "high",
  },
  {
    id: "rtx2080",
    name: "GeForce RTX 2080",
    brand: "NVIDIA",
    vram: 8,
    memoryType: "GDDR6",
    tgp: 215,
    dlss: true,
    fsr: false,
    xess: false,
    rayTracing: true,
    pcie: "3.0",
    releaseYear: 2018,
    gameScore: 88,
    workScore: 83,
    aiScore: 75,
    priceTier: "high",
  },
  {
    id: "rtx2080ti",
    name: "GeForce RTX 2080 Ti",
    brand: "NVIDIA",
    vram: 11,
    memoryType: "GDDR6",
    tgp: 260,
    dlss: true,
    fsr: false,
    xess: false,
    rayTracing: true,
    pcie: "3.0",
    releaseYear: 2018,
    gameScore: 95,
    workScore: 90,
    aiScore: 85,
    priceTier: "high",
  },
  {
    id: "rtx3060",
    name: "GeForce RTX 3060",
    brand: "NVIDIA",
    vram: 12,
    memoryType: "GDDR6",
    tgp: 170,
    dlss: true,
    fsr: false,
    xess: false,
    rayTracing: true,
    pcie: "4.0",
    releaseYear: 2021,
    gameScore: 80,
    workScore: 78,
    aiScore: 75,
    priceTier: "mid",
  },
  {
    id: "rtx3060ti",
    name: "GeForce RTX 3060 Ti",
    brand: "NVIDIA",
    vram: 8,
    memoryType: "GDDR6",
    tgp: 200,
    dlss: true,
    fsr: false,
    xess: false,
    rayTracing: true,
    pcie: "4.0",
    releaseYear: 2020,
    gameScore: 88,
    workScore: 85,
    aiScore: 82,
    priceTier: "mid",
  },
  {
    id: "rtx3070",
    name: "GeForce RTX 3070",
    brand: "NVIDIA",
    vram: 8,
    memoryType: "GDDR6",
    tgp: 220,
    dlss: true,
    fsr: false,
    xess: false,
    rayTracing: true,
    pcie: "4.0",
    releaseYear: 2020,
    gameScore: 92,
    workScore: 88,
    aiScore: 85,
    priceTier: "high",
  },
  {
    id: "rtx3080",
    name: "GeForce RTX 3080",
    brand: "NVIDIA",
    vram: 10,
    memoryType: "GDDR6X",
    tgp: 320,
    dlss: true,
    fsr: false,
    xess: false,
    rayTracing: true,
    pcie: "4.0",
    releaseYear: 2020,
    gameScore: 98,
    workScore: 94,
    aiScore: 92,
    priceTier: "high",
  },
  {
    id: "rtx3090",
    name: "GeForce RTX 3090",
    brand: "NVIDIA",
    vram: 24,
    memoryType: "GDDR6X",
    tgp: 350,
    dlss: true,
    fsr: false,
    xess: false,
    rayTracing: true,
    pcie: "4.0",
    releaseYear: 2020,
    gameScore: 100,
    workScore: 98,
    aiScore: 98,
    priceTier: "enthusiast",
  },
  {
    id: "rtx4060",
    name: "GeForce RTX 4060",
    brand: "NVIDIA",
    vram: 8,
    memoryType: "GDDR6",
    tgp: 115,
    dlss: true,
    fsr: false,
    xess: false,
    rayTracing: true,
    pcie: "4.0",
    releaseYear: 2023,
    gameScore: 75,
    workScore: 70,
    aiScore: 72,
    priceTier: "budget",
  },
  {
    id: "rtx4060ti",
    name: "GeForce RTX 4060 Ti",
    brand: "NVIDIA",
    vram: 16,
    memoryType: "GDDR6",
    tgp: 160,
    dlss: true,
    fsr: false,
    xess: false,
    rayTracing: true,
    pcie: "4.0",
    releaseYear: 2023,
    gameScore: 82,
    workScore: 80,
    aiScore: 82,
    priceTier: "mid",
  },
  {
    id: "rtx4070",
    name: "GeForce RTX 4070",
    brand: "NVIDIA",
    vram: 12,
    memoryType: "GDDR6X",
    tgp: 200,
    dlss: true,
    fsr: false,
    xess: false,
    rayTracing: true,
    pcie: "4.0",
    releaseYear: 2023,
    gameScore: 90,
    workScore: 88,
    aiScore: 90,
    priceTier: "mid",
  },
  {
    id: "rtx4070ti",
    name: "GeForce RTX 4070 Ti",
    brand: "NVIDIA",
    vram: 16,
    memoryType: "GDDR6X",
    tgp: 285,
    dlss: true,
    fsr: false,
    xess: false,
    rayTracing: true,
    pcie: "4.0",
    releaseYear: 2023,
    gameScore: 95,
    workScore: 92,
    aiScore: 94,
    priceTier: "high",
  },
  {
    id: "rtx4080",
    name: "GeForce RTX 4080",
    brand: "NVIDIA",
    vram: 16,
    memoryType: "GDDR6X",
    tgp: 320,
    dlss: true,
    fsr: false,
    xess: false,
    rayTracing: true,
    pcie: "4.0",
    releaseYear: 2023,
    gameScore: 98,
    workScore: 96,
    aiScore: 97,
    priceTier: "high",
  },
  {
    id: "rtx4090",
    name: "GeForce RTX 4090",
    brand: "NVIDIA",
    vram: 24,
    memoryType: "GDDR6X",
    tgp: 450,
    dlss: true,
    fsr: false,
    xess: true,
    rayTracing: true,
    pcie: "4.0",
    releaseYear: 2022,
    gameScore: 100,
    workScore: 99,
    aiScore: 99,
    priceTier: "enthusiast",
  },
  {
    id: "rx560",
    name: "Radeon RX 560",
    brand: "AMD",
    vram: 4,
    memoryType: "GDDR5",
    tgp: 80,
    dlss: false,
    fsr: true,
    xess: false,
    rayTracing: false,
    pcie: "3.0",
    releaseYear: 2017,
    gameScore: 40,
    workScore: 35,
    aiScore: 25,
    priceTier: "budget",
  },
  {
    id: "rx570",
    name: "Radeon RX 570",
    brand: "AMD",
    vram: 8,
    memoryType: "GDDR5",
    tgp: 150,
    dlss: false,
    fsr: true,
    xess: false,
    rayTracing: false,
    pcie: "3.0",
    releaseYear: 2017,
    gameScore: 55,
    workScore: 50,
    aiScore: 35,
    priceTier: "budget",
  },
  {
    id: "rx580",
    name: "Radeon RX 580",
    brand: "AMD",
    vram: 8,
    memoryType: "GDDR5",
    tgp: 185,
    dlss: false,
    fsr: true,
    xess: false,
    rayTracing: false,
    pcie: "3.0",
    releaseYear: 2017,
    gameScore: 65,
    workScore: 60,
    aiScore: 42,
    priceTier: "mid",
  },
  {
    id: "rx590",
    name: "Radeon RX 590",
    brand: "AMD",
    vram: 8,
    memoryType: "GDDR5",
    tgp: 225,
    dlss: false,
    fsr: true,
    xess: false,
    rayTracing: false,
    pcie: "3.0",
    releaseYear: 2018,
    gameScore: 70,
    workScore: 65,
    aiScore: 45,
    priceTier: "mid",
  },
  {
    id: "rx5500xt",
    name: "Radeon RX 5500 XT",
    brand: "AMD",
    vram: 8,
    memoryType: "GDDR6",
    tgp: 130,
    dlss: false,
    fsr: true,
    xess: false,
    rayTracing: false,
    pcie: "4.0",
    releaseYear: 2019,
    gameScore: 65,
    workScore: 60,
    aiScore: 50,
    priceTier: "budget",
  },
  {
    id: "rx5600xt",
    name: "Radeon RX 5600 XT",
    brand: "AMD",
    vram: 6,
    memoryType: "GDDR6",
    tgp: 150,
    dlss: false,
    fsr: true,
    xess: false,
    rayTracing: false,
    pcie: "4.0",
    releaseYear: 2019,
    gameScore: 78,
    workScore: 70,
    aiScore: 62,
    priceTier: "mid",
  },
  {
    id: "rx5700xt",
    name: "Radeon RX 5700 XT",
    brand: "AMD",
    vram: 8,
    memoryType: "GDDR6",
    tgp: 225,
    dlss: false,
    fsr: true,
    xess: false,
    rayTracing: false,
    pcie: "4.0",
    releaseYear: 2019,
    gameScore: 88,
    workScore: 80,
    aiScore: 70,
    priceTier: "high",
  },
  {
    id: "rx6600xt",
    name: "Radeon RX 6600 XT",
    brand: "AMD",
    vram: 8,
    memoryType: "GDDR6",
    tgp: 160,
    dlss: false,
    fsr: true,
    xess: false,
    rayTracing: true,
    pcie: "4.0",
    releaseYear: 2021,
    gameScore: 82,
    workScore: 78,
    aiScore: 70,
    priceTier: "mid",
  },
  {
    id: "rx6700xt",
    name: "Radeon RX 6700 XT",
    brand: "AMD",
    vram: 12,
    memoryType: "GDDR6",
    tgp: 230,
    dlss: false,
    fsr: true,
    xess: false,
    rayTracing: true,
    pcie: "4.0",
    releaseYear: 2021,
    gameScore: 87,
    workScore: 82,
    aiScore: 75,
    priceTier: "high",
  },
  {
    id: "rx6800",
    name: "Radeon RX 6800",
    brand: "AMD",
    vram: 16,
    memoryType: "GDDR6",
    tgp: 250,
    dlss: false,
    fsr: true,
    xess: false,
    rayTracing: true,
    pcie: "4.0",
    releaseYear: 2020,
    gameScore: 92,
    workScore: 88,
    aiScore: 80,
    priceTier: "high",
  },
  {
    id: "rx6800xt",
    name: "Radeon RX 6800 XT",
    brand: "AMD",
    vram: 16,
    memoryType: "GDDR6",
    tgp: 300,
    dlss: false,
    fsr: true,
    xess: false,
    rayTracing: true,
    pcie: "4.0",
    releaseYear: 2020,
    gameScore: 95,
    workScore: 92,
    aiScore: 85,
    priceTier: "high",
  },
  {
    id: "rx6900xt",
    name: "Radeon RX 6900 XT",
    brand: "AMD",
    vram: 16,
    memoryType: "GDDR6",
    tgp: 300,
    dlss: false,
    fsr: true,
    xess: false,
    rayTracing: true,
    pcie: "4.0",
    releaseYear: 2020,
    gameScore: 98,
    workScore: 94,
    aiScore: 88,
    priceTier: "enthusiast",
  },
  {
    id: "rx7600",
    name: "Radeon RX 7600",
    brand: "AMD",
    vram: 8,
    memoryType: "GDDR6",
    tgp: 165,
    dlss: false,
    fsr: true,
    xess: false,
    rayTracing: true,
    pcie: "4.0",
    releaseYear: 2023,
    gameScore: 80,
    workScore: 75,
    aiScore: 70,
    priceTier: "budget",
  },
  {
    id: "rx7700xt",
    name: "Radeon RX 7700 XT",
    brand: "AMD",
    vram: 12,
    memoryType: "GDDR6",
    tgp: 235,
    dlss: false,
    fsr: true,
    xess: false,
    rayTracing: true,
    pcie: "4.0",
    releaseYear: 2023,
    gameScore: 88,
    workScore: 83,
    aiScore: 78,
    priceTier: "high",
  },
  {
    id: "rx7800xt",
    name: "Radeon RX 7800 XT",
    brand: "AMD",
    vram: 16,
    memoryType: "GDDR6",
    tgp: 315,
    dlss: false,
    fsr: true,
    xess: false,
    rayTracing: true,
    pcie: "4.0",
    releaseYear: 2023,
    gameScore: 94,
    workScore: 90,
    aiScore: 85,
    priceTier: "high",
  },
  {
    id: "rx7900xt",
    name: "Radeon RX 7900 XT",
    brand: "AMD",
    vram: 20,
    memoryType: "GDDR6",
    tgp: 300,
    dlss: false,
    fsr: true,
    xess: false,
    rayTracing: true,
    pcie: "5.0",
    releaseYear: 2022,
    gameScore: 96,
    workScore: 92,
    aiScore: 88,
    priceTier: "enthusiast",
  },
  {
    id: "rx7900xtx",
    name: "Radeon RX 7900 XTX",
    brand: "AMD",
    vram: 24,
    memoryType: "GDDR6",
    tgp: 355,
    dlss: false,
    fsr: true,
    xess: false,
    rayTracing: true,
    pcie: "5.0",
    releaseYear: 2022,
    gameScore: 99,
    workScore: 95,
    aiScore: 92,
    priceTier: "enthusiast",
  },
  // RDNA4(RX 9000 시리즈) — AMD 최신 세대. NVIDIA RTX 50 시리즈는 이미 있었는데 AMD 쪽 최신
  // 세대가 통째로 빠져 있어 GPU 브랜드에서 AMD 선택 시 최신 라인업을 고를 수 없던 버그를 해소.
  {
    id: "rx9060xt",
    name: "Radeon RX 9060 XT",
    brand: "AMD",
    vram: 16,
    memoryType: "GDDR6",
    tgp: 150,
    dlss: false,
    fsr: true,
    xess: false,
    rayTracing: true,
    pcie: "5.0",
    releaseYear: 2025,
    gameScore: 80,
    workScore: 74,
    aiScore: 70,
    priceTier: "mid",
  },
  {
    id: "rx9070",
    name: "Radeon RX 9070",
    brand: "AMD",
    vram: 16,
    memoryType: "GDDR6",
    tgp: 220,
    dlss: false,
    fsr: true,
    xess: false,
    rayTracing: true,
    pcie: "5.0",
    releaseYear: 2025,
    gameScore: 92,
    workScore: 87,
    aiScore: 82,
    priceTier: "high",
  },
  {
    id: "rx9070xt",
    name: "Radeon RX 9070 XT",
    brand: "AMD",
    vram: 16,
    memoryType: "GDDR6",
    tgp: 304,
    dlss: false,
    fsr: true,
    xess: false,
    rayTracing: true,
    pcie: "5.0",
    releaseYear: 2025,
    gameScore: 96,
    workScore: 91,
    aiScore: 86,
    priceTier: "high",
  },
  {
    id: "arca380",
    name: "Intel Arc A380",
    brand: "Intel",
    vram: 8,
    memoryType: "GDDR6",
    tgp: 75,
    dlss: false,
    fsr: false,
    xess: true,
    rayTracing: true,
    pcie: "4.0",
    releaseYear: 2022,
    gameScore: 55,
    workScore: 50,
    aiScore: 53,
    priceTier: "budget",
  },
  {
    id: "arca580",
    name: "Intel Arc A580",
    brand: "Intel",
    vram: 8,
    memoryType: "GDDR6",
    tgp: 120,
    dlss: false,
    fsr: false,
    xess: true,
    rayTracing: true,
    pcie: "4.0",
    releaseYear: 2023,
    gameScore: 65,
    workScore: 60,
    aiScore: 64,
    priceTier: "mid",
  },
  {
    id: "arca750",
    name: "Intel Arc A750",
    brand: "Intel",
    vram: 8,
    memoryType: "GDDR6",
    tgp: 225,
    dlss: false,
    fsr: false,
    xess: true,
    rayTracing: true,
    pcie: "4.0",
    releaseYear: 2023,
    gameScore: 72,
    workScore: 68,
    aiScore: 75,
    priceTier: "mid",
  },
  {
    id: "arca770",
    name: "Intel Arc A770",
    brand: "Intel",
    vram: 16,
    memoryType: "GDDR6",
    tgp: 225,
    dlss: false,
    fsr: false,
    xess: true,
    rayTracing: true,
    pcie: "4.0",
    releaseYear: 2023,
    gameScore: 82,
    workScore: 80,
    aiScore: 85,
    priceTier: "high",
  },
];

// src/constants/hardwareData.ts(물리 스펙 전용 마스터)에서 curatedGpus에 없는 모델만 골라
// PCIe/메모리 타입/점수 등을 추정해 합친다.
const additionalGpus: GPU[] = buildAdditionalGpus(curatedGpus, getAllGpus());

export const gpus: GPU[] = [...curatedGpus, ...additionalGpus];
