import { motherboardMasterDb, type MotherboardItem } from "./hardwareMasterDb";

export interface MotherBoard {
  id: string;

  name: string;
  brand: "ASUS" | "MSI" | "GIGABYTE" | "ASRock";

  socket: "AM5" | "AM4" | "LGA1700" | "LGA1851";

  chipset: string;

  ddr: "DDR5" | "DDR4";

  maxMemory: number;

  memorySlots: number;

  pcie: "4.0" | "5.0";

  m2Slots: number;

  sataPorts: number;

  supportedNvmeGenerations: Array<3 | 4 | 5>;

  wifi: boolean;

  formFactor?: "ATX" | "mATX" | "ITX";

  releaseYear: number;

  gameScore: number;
  workScore: number;
  aiScore: number;

  /**
   * 보드 품질 점수(0~100) — VRM 페이즈/전력단·방열 설계·BIOS 성숙도 기반 안정성 등급.
   * 가격이 아니라 실제 내구성을 담보하기 위한 값. 레거시 카탈로그 항목은 데이터가 없어
   * undefined이며, 이 경우 추천 엔진의 품질 하한선 필터를 통과한 것으로 간주한다
   * (recommender.ts의 MIN_BOARD_QUALITY_BY_TDP 참고).
   */
  qualityScore?: number;

  /** 실거래가(KRW) — 있으면 priceTier 대신 이 값을 우선 사용한다(recommender.ts 참고). */
  price?: number;

  priceTier?: "budget" | "mid" | "high";
}

export const motherboards: MotherBoard[] = [
  {
    id: "z890-aorus-master",
    name: "Z890 AORUS MASTER",
    brand: "GIGABYTE",
    socket: "LGA1851",
    chipset: "Z890",
    ddr: "DDR5",
    maxMemory: 256,
    memorySlots: 4,
    pcie: "5.0",
    m2Slots: 5,
    sataPorts: 4,
    supportedNvmeGenerations: [4, 5],
    wifi: true,
    releaseYear: 2025,
    gameScore: 99,
    workScore: 99,
    aiScore: 99,
    price: 620_000,
    priceTier: "high",
  },
  {
    id: "z790-tuf-gaming",
    name: "Z790 TUF Gaming Plus",
    brand: "ASUS",
    socket: "LGA1700",
    chipset: "Z790",
    ddr: "DDR5",
    maxMemory: 128,
    memorySlots: 4,
    pcie: "5.0",
    m2Slots: 4,
    sataPorts: 4,
    supportedNvmeGenerations: [4, 5],
    wifi: true,
    releaseYear: 2023,
    gameScore: 95,
    workScore: 95,
    aiScore: 94,
    price: 320_000,
    priceTier: "high",
  },
  {
    id: "b860-gaming-x",
    name: "B860 Gaming X WiFi",
    brand: "GIGABYTE",
    socket: "LGA1851",
    chipset: "B860",
    ddr: "DDR5",
    maxMemory: 256,
    memorySlots: 4,
    pcie: "5.0",
    m2Slots: 4,
    sataPorts: 4,
    supportedNvmeGenerations: [4, 5],
    wifi: true,
    releaseYear: 2025,
    gameScore: 95,
    workScore: 95,
    aiScore: 95,
    price: 270_000,
    priceTier: "mid",
  },
  {
    id: "b760-aorus-elite",
    name: "B760 AORUS ELITE AX",
    brand: "GIGABYTE",
    socket: "LGA1700",
    chipset: "B760",
    ddr: "DDR5",
    maxMemory: 192,
    memorySlots: 4,
    pcie: "5.0",
    m2Slots: 4,
    sataPorts: 4,
    supportedNvmeGenerations: [4, 5],
    wifi: true,
    releaseYear: 2024,
    gameScore: 90,
    workScore: 90,
    aiScore: 89,
    price: 250_000,
    priceTier: "mid",
  },
  {
    id: "h610m-k",
    name: "H610M-K",
    brand: "ASUS",
    socket: "LGA1700",
    chipset: "H610",
    ddr: "DDR4",
    maxMemory: 64,
    memorySlots: 2,
    pcie: "4.0",
    m2Slots: 2,
    sataPorts: 4,
    supportedNvmeGenerations: [3, 4],
    wifi: false,
    releaseYear: 2023,
    gameScore: 72,
    workScore: 72,
    aiScore: 70,
    price: 90_000,
    priceTier: "budget",
  },
  {
    id: "x870e-a-elite",
    name: "X870E APEX",
    brand: "ASUS",
    socket: "AM5",
    chipset: "X870",
    ddr: "DDR5",
    maxMemory: 256,
    memorySlots: 4,
    pcie: "5.0",
    m2Slots: 4,
    sataPorts: 4,
    supportedNvmeGenerations: [4, 5],
    wifi: true,
    releaseYear: 2025,
    gameScore: 98,
    workScore: 98,
    aiScore: 98,
    price: 720_000,
    priceTier: "high",
  },
  {
    id: "x670e-gaming-plus",
    name: "X670E Gaming Plus",
    brand: "MSI",
    socket: "AM5",
    chipset: "X670",
    ddr: "DDR5",
    maxMemory: 128,
    memorySlots: 4,
    pcie: "5.0",
    m2Slots: 4,
    sataPorts: 4,
    supportedNvmeGenerations: [4, 5],
    wifi: true,
    releaseYear: 2023,
    gameScore: 95,
    workScore: 94,
    aiScore: 94,
    price: 380_000,
    priceTier: "high",
  },
  {
    id: "b650m-aorus-elite",
    name: "B650M AORUS ELITE",
    brand: "GIGABYTE",
    socket: "AM5",
    chipset: "B650",
    ddr: "DDR5",
    maxMemory: 192,
    memorySlots: 4,
    pcie: "5.0",
    m2Slots: 4,
    sataPorts: 4,
    supportedNvmeGenerations: [4, 5],
    wifi: true,
    releaseYear: 2024,
    gameScore: 93,
    workScore: 92,
    aiScore: 92,
    price: 230_000,
    priceTier: "mid",
  },
  {
    id: "a620m-aorus-elite",
    name: "A620M AORUS ELITE",
    brand: "GIGABYTE",
    socket: "AM5",
    chipset: "A620",
    ddr: "DDR5",
    maxMemory: 96,
    memorySlots: 2,
    pcie: "4.0",
    m2Slots: 2,
    sataPorts: 4,
    supportedNvmeGenerations: [3, 4],
    wifi: false,
    releaseYear: 2024,
    gameScore: 80,
    workScore: 79,
    aiScore: 78,
    price: 130_000,
    priceTier: "budget",
  },
  {
    id: "b550m-aorus-pro",
    name: "B550M AORUS PRO",
    brand: "GIGABYTE",
    socket: "AM4",
    chipset: "B550",
    ddr: "DDR4",
    maxMemory: 128,
    memorySlots: 4,
    pcie: "4.0",
    m2Slots: 3,
    sataPorts: 6,
    supportedNvmeGenerations: [3, 4],
    wifi: false,
    releaseYear: 2020,
    gameScore: 78,
    workScore: 78,
    aiScore: 74,
    price: 140_000,
    priceTier: "budget",
  },

  // ── hardwareSeed.ts 병합분 (2026년 중반 시드 — qualityScore 기반 안정성 등급 보유) ──
  // qualityScore 필드가 있는 항목은 추천 엔진에서 최저가가 아닌 품질 우선으로 선택된다.
  {
    id: "mb-amd-b850-tomahawk",
    name: "MSI MAG B850 Tomahawk MAX WiFi",
    brand: "MSI",
    socket: "AM5",
    chipset: "B850",
    ddr: "DDR5",
    maxMemory: 256,
    memorySlots: 4,
    pcie: "5.0",
    m2Slots: 4,
    sataPorts: 4,
    supportedNvmeGenerations: [4, 5],
    wifi: true,
    formFactor: "ATX",
    releaseYear: 2025,
    gameScore: 80,
    workScore: 80,
    aiScore: 80,
    qualityScore: 80,
    price: 330_000,
  },
  {
    id: "mb-amd-x870-tomahawk",
    name: "MSI MAG X870 Tomahawk WiFi",
    brand: "MSI",
    socket: "AM5",
    chipset: "X870",
    ddr: "DDR5",
    maxMemory: 256,
    memorySlots: 4,
    pcie: "5.0",
    m2Slots: 4,
    sataPorts: 4,
    supportedNvmeGenerations: [4, 5],
    wifi: true,
    formFactor: "ATX",
    releaseYear: 2025,
    gameScore: 82,
    workScore: 82,
    aiScore: 82,
    qualityScore: 82,
    price: 335_000,
  },
  {
    id: "mb-amd-x870-aorus-elite",
    name: "Gigabyte X870 AORUS Elite WiFi7",
    brand: "GIGABYTE",
    socket: "AM5",
    chipset: "X870",
    ddr: "DDR5",
    maxMemory: 256,
    memorySlots: 4,
    pcie: "5.0",
    m2Slots: 4,
    sataPorts: 4,
    supportedNvmeGenerations: [4, 5],
    wifi: true,
    formFactor: "ATX",
    releaseYear: 2025,
    gameScore: 86,
    workScore: 86,
    aiScore: 86,
    qualityScore: 86,
    price: 350_000,
  },
  {
    id: "mb-amd-x870-tuf-plus",
    name: "ASUS TUF Gaming X870-Plus WiFi",
    brand: "ASUS",
    socket: "AM5",
    chipset: "X870",
    ddr: "DDR5",
    maxMemory: 256,
    memorySlots: 4,
    pcie: "5.0",
    m2Slots: 4,
    sataPorts: 4,
    supportedNvmeGenerations: [4, 5],
    wifi: true,
    formFactor: "ATX",
    releaseYear: 2025,
    gameScore: 84,
    workScore: 84,
    aiScore: 84,
    qualityScore: 84,
    price: 420_000,
  },
  {
    id: "mb-amd-x870e-taichi",
    name: "ASRock X870E Taichi",
    brand: "ASRock",
    socket: "AM5",
    chipset: "X870E",
    ddr: "DDR5",
    maxMemory: 256,
    memorySlots: 4,
    pcie: "5.0",
    m2Slots: 5,
    sataPorts: 6,
    supportedNvmeGenerations: [4, 5],
    wifi: true,
    formFactor: "ATX", // 실제는 EATX에 가까운 플래그십 크기 — 케이스 호환 로직 추가 시 조정
    releaseYear: 2025,
    gameScore: 95,
    workScore: 95,
    aiScore: 95,
    qualityScore: 95,
    price: 650_000,
  },
  {
    id: "mb-amd-b850i-lightning",
    name: "ASRock B850I Lightning WiFi",
    brand: "ASRock",
    socket: "AM5",
    chipset: "B850",
    ddr: "DDR5",
    maxMemory: 96,
    memorySlots: 2,
    pcie: "5.0",
    m2Slots: 2,
    sataPorts: 2,
    supportedNvmeGenerations: [4, 5],
    wifi: true,
    formFactor: "ITX",
    releaseYear: 2025,
    gameScore: 70,
    workScore: 70,
    aiScore: 70,
    qualityScore: 70,
    price: 300_000,
  },
  {
    id: "mb-amd-b650-tuf-plus",
    name: "ASUS TUF Gaming B650-Plus WiFi (레거시·가성비)",
    brand: "ASUS",
    socket: "AM5",
    chipset: "B650",
    ddr: "DDR5",
    maxMemory: 128,
    memorySlots: 4,
    pcie: "4.0",
    m2Slots: 3,
    sataPorts: 4,
    supportedNvmeGenerations: [3, 4],
    wifi: true,
    formFactor: "ATX",
    releaseYear: 2023,
    gameScore: 66,
    workScore: 66,
    aiScore: 66,
    qualityScore: 66,
    price: 250_000,
  },
  {
    id: "mb-intel-z890-tomahawk",
    name: "MSI MAG Z890 Tomahawk WiFi",
    brand: "MSI",
    socket: "LGA1851",
    chipset: "Z890",
    ddr: "DDR5",
    maxMemory: 256,
    memorySlots: 4,
    pcie: "5.0",
    m2Slots: 5,
    sataPorts: 4,
    supportedNvmeGenerations: [4, 5],
    wifi: true,
    formFactor: "ATX",
    releaseYear: 2025,
    gameScore: 83,
    workScore: 83,
    aiScore: 83,
    qualityScore: 83,
    price: 360_000,
  },
  {
    id: "mb-intel-z890-gaming-plus",
    name: "MSI Z890 Gaming Plus WiFi",
    brand: "MSI",
    socket: "LGA1851",
    chipset: "Z890",
    ddr: "DDR5",
    maxMemory: 256,
    memorySlots: 4,
    pcie: "5.0",
    m2Slots: 4,
    sataPorts: 4,
    supportedNvmeGenerations: [4, 5],
    wifi: true,
    formFactor: "ATX",
    releaseYear: 2025,
    gameScore: 74,
    workScore: 74,
    aiScore: 74,
    qualityScore: 74,
    price: 300_000,
  },
  {
    id: "mb-intel-b860-tuf-plus",
    name: "ASUS TUF Gaming B860-Plus WiFi",
    brand: "ASUS",
    socket: "LGA1851",
    chipset: "B860",
    ddr: "DDR5",
    maxMemory: 256,
    memorySlots: 4,
    pcie: "5.0",
    m2Slots: 4,
    sataPorts: 4,
    supportedNvmeGenerations: [4, 5],
    wifi: true,
    formFactor: "ATX",
    releaseYear: 2025,
    gameScore: 78,
    workScore: 78,
    aiScore: 78,
    qualityScore: 78,
    price: 290_000,
  },
  {
    id: "mb-intel-b860-pro-rs",
    name: "ASRock B860 Pro RS WiFi",
    brand: "ASRock",
    socket: "LGA1851",
    chipset: "B860",
    ddr: "DDR5",
    maxMemory: 192,
    memorySlots: 4,
    pcie: "5.0",
    m2Slots: 3,
    sataPorts: 4,
    supportedNvmeGenerations: [4, 5],
    wifi: true,
    formFactor: "ATX",
    releaseYear: 2025,
    gameScore: 72,
    workScore: 72,
    aiScore: 72,
    qualityScore: 72,
    price: 250_000,
  },
  {
    id: "mb-intel-b760-tuf-plus",
    name: "ASUS TUF Gaming B760-Plus WiFi (레거시)",
    brand: "ASUS",
    socket: "LGA1700",
    chipset: "B760",
    ddr: "DDR5",
    maxMemory: 128,
    memorySlots: 4,
    pcie: "4.0",
    m2Slots: 3,
    sataPorts: 4,
    supportedNvmeGenerations: [3, 4],
    wifi: true,
    formFactor: "ATX",
    releaseYear: 2023,
    gameScore: 63,
    workScore: 63,
    aiScore: 63,
    qualityScore: 63,
    price: 230_000,
  },
];

export const motherboardMasterItems: MotherboardItem[] = motherboardMasterDb;